/*
 * Vst3Instrument.cpp - instrument plugin hosting native VST3 instruments
 *
 * This file is part of LMMS - https://lmms.io
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public
 * License along with this program (see COPYING); if not, write to the
 * Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA 02110-1301 USA.
 *
 */

#include "Vst3Instrument.h"

#include <QDomDocument>
#include <QDomElement>
#include <QFileInfo>
#include <QHBoxLayout>
#include <QIcon>
#include <QInputDialog>
#include <QLabel>
#include <QMutexLocker>
#include <QPushButton>
#include <QTabWidget>
#include <QVBoxLayout>

#include <algorithm>

#include "AudioEngine.h"
#include "Engine.h"
#include "FileDialog.h"
#include "InstrumentPlayHandle.h"
#include "InstrumentTrack.h"
#include "InstrumentTrackWindow.h"
#include "PathUtil.h"
#include "SampleFrame.h"
#include "Song.h"
#include "Vst3Plugin.h"

#include "embed.h"
#include "plugin_export.h"

namespace lmms
{


extern "C"
{

Plugin::Descriptor PLUGIN_EXPORT vst3instrument_plugin_descriptor =
{
	LMMS_STRINGIFY( PLUGIN_NAME ),
	"VST3",
	QT_TRANSLATE_NOOP( "PluginBrowser",
			"plugin for using native VST3 instruments inside LMMS." ),
	"LMMS Developers",
	0x0100,
	Plugin::Type::Instrument,
	new PluginPixmapLoader("logo"),
	"vst3",
	nullptr,
} ;

}




Vst3Instrument::Vst3Instrument(InstrumentTrack* track) :
	Instrument(track, &vst3instrument_plugin_descriptor, nullptr,
			Flag::IsSingleStreamed | Flag::IsMidiBased)
{
	// we need a play-handle which cares for calling play()
	auto iph = new InstrumentPlayHandle(this, track);
	Engine::audioEngine()->addPlayHandle(iph);
}




Vst3Instrument::~Vst3Instrument()
{
	Engine::audioEngine()->removePlayHandlesOfTypes(instrumentTrack(),
			PlayHandle::Type::NotePlayHandle | PlayHandle::Type::InstrumentPlayHandle);
	closePlugin();
}




void Vst3Instrument::closePlugin()
{
	QMutexLocker lock(&m_pluginMutex);
	m_plugin.reset();
	m_pluginFile.clear();
}




void Vst3Instrument::loadFile(const QString& file)
{
	{
		QMutexLocker lock(&m_pluginMutex);
		m_plugin.reset();

		bool error = false;
		QString absFile = PathUtil::toAbsolute(file, &error);
		if (error) { absFile = file; }

		auto plugin = std::make_unique<Vst3Plugin>(absFile, Vst3Plugin::Kind::Instrument);
		if (plugin->failed())
		{
			collectErrorForUI(Vst3Plugin::tr("The VST3 plugin %1 could not be loaded: %2")
					.arg(file, plugin->errorString()));
		}
		else
		{
			m_plugin = std::move(plugin);
			m_pluginFile = PathUtil::toShortestRelative(absFile);

			// expose the plug-in's parameters as LMMS automatable models
			m_plugin->createParameterModels(this);

			// route MIDI generated by the plug-in (arpeggiators etc.) to the
			// track's MIDI output port; MidiPort ignores the events unless
			// the user enabled MIDI output for the track
			m_plugin->setMidiOutputHandler([this](const MidiEvent& event) {
				auto track = instrumentTrack();
				if (track != nullptr) { track->midiPort()->processOutEvent(event, TimePos()); }
			});
		}
	}

	// the GUI is shown embedded in the instrument view's "GUI" tab (see
	// Vst3InstrumentView), so we do not open a separate editor window here

	emit pluginChanged();
	emit dataChanged();
}




void Vst3Instrument::play(SampleFrame* workingBuffer)
{
	const f_cnt_t frames = Engine::audioEngine()->framesPerPeriod();

	if (m_pluginMutex.tryLock(Engine::getSong()->isExporting() ? -1 : 0))
	{
		if (m_plugin != nullptr)
		{
			m_plugin->process(nullptr, workingBuffer, frames);
		}
		else
		{
			zeroSampleFrames(workingBuffer, frames);
		}
		m_pluginMutex.unlock();
	}
	else
	{
		zeroSampleFrames(workingBuffer, frames);
	}
}




bool Vst3Instrument::handleMidiEvent(const MidiEvent& event, const TimePos&, f_cnt_t offset)
{
	if (m_pluginMutex.tryLock(10))
	{
		if (m_plugin != nullptr) { m_plugin->queueMidiEvent(event, offset); }
		m_pluginMutex.unlock();
	}
	return true;
}




void Vst3Instrument::saveSettings(QDomDocument& doc, QDomElement& element)
{
	QMutexLocker lock(&m_pluginMutex);
	if (m_plugin == nullptr) { return; }

	element.setAttribute("plugin", m_pluginFile);
	element.setAttribute("guivisible", m_plugin->editorVisible() ? 1 : 0);
	m_plugin->saveState(doc, element);
	m_plugin->saveParameterModels(doc, element);
}




void Vst3Instrument::loadSettings(const QDomElement& element)
{
	const QString file = element.attribute("plugin");
	if (file.isEmpty()) { return; }

	loadFile(file);

	QMutexLocker lock(&m_pluginMutex);
	if (m_plugin == nullptr) { return; }

	m_plugin->loadState(element);
	m_plugin->loadParameterModels(element);
	// GUI is shown embedded in the instrument view, not as a separate window
}




QString Vst3Instrument::nodeName() const
{
	return vst3instrument_plugin_descriptor.name;
}




gui::PluginView* Vst3Instrument::instantiateView(QWidget* parent)
{
	return new gui::Vst3InstrumentView(this, parent);
}




namespace gui
{


Vst3InstrumentView::Vst3InstrumentView(Vst3Instrument* instrument, QWidget* parent) :
	InstrumentView(instrument, parent)
{
	// always resizable so the embedded plug-in GUI can grow the window
	m_resizable = true;

	auto outer = new QVBoxLayout(this);
	outer->setContentsMargins(4, 4, 4, 4);

	m_tabs = new QTabWidget(this);
	outer->addWidget(m_tabs);

	// GUI tab: a compact header (name + open button) above the embedded editor
	auto guiTab = new QWidget(m_tabs);
	m_guiLayout = new QVBoxLayout(guiTab);
	m_guiLayout->setContentsMargins(6, 6, 6, 6);

	auto header = new QHBoxLayout();
	m_nameLabel = new QLabel(tr("No plugin loaded"), guiTab);
	m_nameLabel->setWordWrap(true);
	m_openButton = new QPushButton(tr("Open VST3 plugin..."), guiTab);
	connect(m_openButton, &QPushButton::clicked, this, &Vst3InstrumentView::openPlugin);
	header->addWidget(m_nameLabel, 1);
	header->addWidget(m_openButton, 0);
	m_guiLayout->addLayout(header);
	m_tabs->addTab(guiTab, tr("GUI"));

	// Parameters tab (filled lazily with the plug-in's knobs)
	m_paramsTab = new QWidget(m_tabs);
	auto paramsLayout = new QVBoxLayout(m_paramsTab);
	paramsLayout->setContentsMargins(0, 0, 0, 0);
	m_tabs->addTab(m_paramsTab, tr("Parameters"));

	updateName();
}




void Vst3InstrumentView::showEvent(QShowEvent* event)
{
	InstrumentView::showEvent(event);
	// drop the plug-in-logo window icon (the red square in the title bar)
	if (auto* w = instrumentTrackWindow()) { w->setWindowIcon(QIcon()); }
	// embed the native editor the first time the window is shown, so plug-in
	// GUIs aren't created before the instrument is actually opened
	ensureEmbedded();
}




void Vst3InstrumentView::ensureEmbedded()
{
	if (m_embedded) { return; }
	auto m = castModel<Vst3Instrument>();
	auto p = (m != nullptr) ? m->plugin() : nullptr;
	if (p == nullptr) { return; }
	m_embedded = true;

	if (p->hasEditor())
	{
		if (QWidget* editor = p->createEmbeddedEditor(m_tabs->widget(0)))
		{
			m_guiLayout->addWidget(editor, 1);
			connect(p, &Vst3Plugin::editorResized, this, &Vst3InstrumentView::fitWindow);
		}
	}
	else
	{
		m_guiLayout->addStretch();
	}

	if (QWidget* params = p->createParameterWidget(m_paramsTab))
	{
		m_paramsTab->layout()->addWidget(params);
	}

	fitWindow();
}




void Vst3InstrumentView::fitWindow()
{
	// Grow the instrument window to fit the embedded GUI. The window sizes this
	// view (the "Plugin" tab) to (window height - 180) / (window width - 4) via
	// InstrumentTrackWindow::adjustTabSize, so we size the window from this
	// view's preferred size plus that fixed chrome, instead of the window's own
	// sizeHint (which underestimates the deeply-nested plug-in GUI and clips it).
	auto* w = instrumentTrackWindow();
	if (w == nullptr) { return; }

	if (layout() != nullptr) { layout()->activate(); }
	const QSize hint = sizeHint();
	constexpr int chromeHeight = 180;  // matches adjustTabSize()
	constexpr int chromeWidth = 8;
	const int wantW = std::max(w->width(), hint.width() + chromeWidth);
	const int wantH = std::max(w->height(), hint.height() + chromeHeight);
	if (wantW != w->width() || wantH != w->height())
	{
		w->resize(wantW, wantH);
		if (w->parentWidget() != nullptr)
		{
			w->parentWidget()->resize(w->parentWidget()->sizeHint());
		}
	}
}




void Vst3InstrumentView::modelChanged()
{
	auto m = castModel<Vst3Instrument>();
	connect(m, &Vst3Instrument::pluginChanged, this, &Vst3InstrumentView::updateName);
	updateName();
}




void Vst3InstrumentView::updateName()
{
	auto m = castModel<Vst3Instrument>();
	if (m != nullptr && m->plugin() != nullptr)
	{
		m_nameLabel->setText(m->plugin()->name() + " - " + m->plugin()->vendor());
	}
	else
	{
		m_nameLabel->setText(tr("No plugin loaded"));
	}
}




void Vst3InstrumentView::openPlugin()
{
	auto m = castModel<Vst3Instrument>();
	if (m == nullptr) { return; }

	// list all installed VST3 modules from the standard locations
	QStringList paths;
	for (const auto& path : Vst3Plugin::modulePaths())
	{
		paths << QString::fromStdString(path);
	}

	QStringList names;
	for (const QString& p : paths)
	{
		names << QFileInfo(p).completeBaseName();
	}
	names << tr("[ Browse for file... ]");

	bool ok = false;
	const QString chosen = QInputDialog::getItem(this, tr("Open VST3 plugin"),
			tr("Installed VST3 plugins:"), names, 0, false, &ok);
	if (!ok || chosen.isEmpty()) { return; }

	QString file;
	const int index = names.indexOf(chosen);
	if (index >= 0 && index < paths.size())
	{
		file = paths[index];
	}
	else
	{
		FileDialog ofd(nullptr, tr("Open VST3 plugin"));
		ofd.setNameFilters({tr("VST3 plugins (*.vst3)")});
		if (ofd.exec() != QDialog::Accepted || ofd.selectedFiles().isEmpty()) { return; }
		file = ofd.selectedFiles()[0];
	}

	Engine::audioEngine()->requestChangeInModel();
	m->loadFile(file);
	Engine::audioEngine()->doneChangeInModel();

	// embed the newly loaded plug-in's GUI/parameters (for a fresh instrument
	// that had no plug-in when the window was first shown)
	ensureEmbedded();
}




} // namespace gui


extern "C"
{

// necessary for getting instance out of shared lib
PLUGIN_EXPORT Plugin* lmms_plugin_main(Model* m, void*)
{
	return new Vst3Instrument(static_cast<InstrumentTrack*>(m));
}

}


} // namespace lmms
