/*
 * Vst3Instrument.cpp - instrument plugin hosting native VST3 instruments
 *
 * This file is part of LMMS - https://lmms.io
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public
 * License along with this program (see COPYING); if not, write to the
 * Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA 02110-1301 USA.
 *
 */

#include "Vst3Instrument.h"

#include <QDir>
#include <QDomDocument>
#include <QDomElement>
#include <QFileInfo>
#include <QGridLayout>
#include <QHBoxLayout>
#include <QIcon>
#include <QLabel>
#include <QLineEdit>
#include <QMutexLocker>
#include <QPushButton>
#include <QRegularExpression>
#include <QVBoxLayout>

#include <algorithm>

#include "AudioBusHandle.h"
#include "AudioEngine.h"
#include "AutomatableButton.h"
#include "ConfigManager.h"
#include "DataFile.h"
#include "EffectRackView.h"
#include "Engine.h"
#include "FileDialog.h"
#include "InstrumentFunctionViews.h"
#include "InstrumentMidiIOView.h"
#include "InstrumentPlayHandle.h"
#include "InstrumentTrack.h"
#include "InstrumentTrackWindow.h"
#include "Knob.h"
#include "LcdSpinBox.h"
#include "LedCheckBox.h"
#include "PathUtil.h"
#include "PianoView.h"
#include "SampleFrame.h"
#include "Song.h"
#include "Vst3Plugin.h"
#include "Vst3PluginView.h"

#include "embed.h"
#include "plugin_export.h"

namespace lmms
{


extern "C"
{

Plugin::Descriptor PLUGIN_EXPORT vst3instrument_plugin_descriptor =
{
	LMMS_STRINGIFY( PLUGIN_NAME ),
	"VST3",
	QT_TRANSLATE_NOOP( "PluginBrowser",
			"plugin for using native VST3 instruments inside KitsuneTone." ),
	"KitsuneTone contributors",
	0x0100,
	Plugin::Type::Instrument,
	new PluginPixmapLoader("logo"),
	"vst3",
	nullptr,
} ;

}




Vst3Instrument::Vst3Instrument(InstrumentTrack* track) :
	Instrument(track, &vst3instrument_plugin_descriptor, nullptr,
			Flag::IsSingleStreamed | Flag::IsMidiBased)
{
	// we need a play-handle which cares for calling play()
	auto iph = new InstrumentPlayHandle(this, track);
	Engine::audioEngine()->addPlayHandle(iph);
}




Vst3Instrument::~Vst3Instrument()
{
	Engine::audioEngine()->removePlayHandlesOfTypes(instrumentTrack(),
			PlayHandle::Type::NotePlayHandle | PlayHandle::Type::InstrumentPlayHandle);
	closePlugin();
}




void Vst3Instrument::closePlugin()
{
	QMutexLocker lock(&m_pluginMutex);
	m_plugin.reset();
	m_pluginFile.clear();
}




void Vst3Instrument::loadFile(const QString& file)
{
	{
		QMutexLocker lock(&m_pluginMutex);
		m_plugin.reset();

		bool error = false;
		QString absFile = PathUtil::toAbsolute(file, &error);
		if (error) { absFile = file; }

		auto plugin = std::make_unique<Vst3Plugin>(absFile, Vst3Plugin::Kind::Instrument);
		if (plugin->failed())
		{
			collectErrorForUI(Vst3Plugin::tr("The VST3 plugin %1 could not be loaded: %2")
					.arg(file, plugin->errorString()));
		}
		else
		{
			m_plugin = std::move(plugin);
			m_pluginFile = PathUtil::toShortestRelative(absFile);

			// expose the plug-in's parameters as LMMS automatable models
			m_plugin->createParameterModels(this);

			// route MIDI generated by the plug-in (arpeggiators etc.) to the
			// track's MIDI output port; MidiPort ignores the events unless
			// the user enabled MIDI output for the track
			m_plugin->setMidiOutputHandler([this](const MidiEvent& event) {
				auto track = instrumentTrack();
				if (track != nullptr) { track->midiPort()->processOutEvent(event, TimePos()); }
			});
		}
	}

	// the GUI is shown embedded in the instrument view's "GUI" tab (see
	// Vst3InstrumentView), so we do not open a separate editor window here

	emit pluginChanged();
	emit dataChanged();
}




void Vst3Instrument::play(SampleFrame* workingBuffer)
{
	const f_cnt_t frames = Engine::audioEngine()->framesPerPeriod();

	if (m_pluginMutex.tryLock(Engine::getSong()->isExporting() ? -1 : 0))
	{
		if (m_plugin != nullptr)
		{
			m_plugin->process(nullptr, workingBuffer, frames);
		}
		else
		{
			zeroSampleFrames(workingBuffer, frames);
		}
		m_pluginMutex.unlock();
	}
	else
	{
		zeroSampleFrames(workingBuffer, frames);
	}
}




bool Vst3Instrument::handleMidiEvent(const MidiEvent& event, const TimePos&, f_cnt_t offset)
{
	if (m_pluginMutex.tryLock(10))
	{
		if (m_plugin != nullptr) { m_plugin->queueMidiEvent(event, offset); }
		m_pluginMutex.unlock();
	}
	return true;
}




void Vst3Instrument::saveSettings(QDomDocument& doc, QDomElement& element)
{
	QMutexLocker lock(&m_pluginMutex);
	if (m_plugin == nullptr) { return; }

	element.setAttribute("plugin", m_pluginFile);
	element.setAttribute("guivisible", m_plugin->editorVisible() ? 1 : 0);
	m_plugin->saveState(doc, element);
	m_plugin->saveParameterModels(doc, element);
}




void Vst3Instrument::loadSettings(const QDomElement& element)
{
	const QString file = element.attribute("plugin");
	if (file.isEmpty()) { return; }

	loadFile(file);

	QMutexLocker lock(&m_pluginMutex);
	if (m_plugin == nullptr) { return; }

	m_plugin->loadState(element);
	m_plugin->loadParameterModels(element);
	// GUI is shown embedded in the instrument view, not as a separate window
}




QString Vst3Instrument::nodeName() const
{
	return vst3instrument_plugin_descriptor.name;
}




gui::PluginView* Vst3Instrument::instantiateView(QWidget* parent)
{
	return new gui::Vst3InstrumentView(this, parent);
}




namespace gui
{


Vst3InstrumentView::Vst3InstrumentView(Vst3Instrument* instrument, QWidget* parent) :
	InstrumentView(instrument, parent)
{
	// always resizable so the embedded plug-in GUI can grow the window
	m_resizable = true;

	auto outer = new QVBoxLayout(this);
	outer->setContentsMargins(0, 0, 0, 0);

	connect(instrument, &Vst3Instrument::pluginChanged,
			this, &Vst3InstrumentView::buildTabs);
	buildTabs();
}




void Vst3InstrumentView::buildTabs()
{
	delete m_pluginView;
	m_pluginView = nullptr;

	auto* instrument = castModel<Vst3Instrument>();
	if (instrument == nullptr) { return; }
	auto* track = instrument->instrumentTrack();
	if (track == nullptr) { return; }

	m_pluginView = new Vst3PluginView(instrument->plugin(), this);
	layout()->addWidget(m_pluginView);
	m_pluginView->setContentsChangedCallback([this] { fitWindow(); });

	// Match the VST3 effect dialog first: GUI / Parameters / MIDI.
	auto* midiView = new InstrumentMidiIOView(m_pluginView);
	midiView->setModel(track->midiPort());
	m_pluginView->addTab(midiView, QStringLiteral("MIDI"));

	// Instrument-only functionality follows as additional tabs.
	m_pluginView->addTab(createTrackTab(track), QStringLiteral("トラック"));

	auto* functions = new QWidget(m_pluginView);
	auto* functionsLayout = new QVBoxLayout(functions);
	functionsLayout->setContentsMargins(4, 4, 4, 4);
	auto* noteStackingView = new InstrumentFunctionNoteStackingView(
			track->noteStacking(), functions);
	noteStackingView->setModel(track->noteStacking());
	functionsLayout->addWidget(noteStackingView);
	auto* arpeggioView = new InstrumentFunctionArpeggioView(
			track->arpeggio(), functions);
	arpeggioView->setModel(track->arpeggio());
	functionsLayout->addWidget(arpeggioView);
	functionsLayout->addStretch();
	m_pluginView->addTab(functions, QStringLiteral("アルペジオ/コード"));

	auto* effects = new EffectRackView(
			track->audioBusHandle()->effects(), m_pluginView);
	m_pluginView->addTab(effects, QStringLiteral("エフェクト"));

	if (instrument->isMidiBased())
	{
		track->microtuner()->enabledModel()->setValue(false);
	}

	resize(360, 300);
	if (isVisible()) { ensureEmbedded(); }
}




QWidget* Vst3InstrumentView::createTrackTab(InstrumentTrack* track)
{
	auto* page = new QWidget(m_pluginView);
	auto* outer = new QVBoxLayout(page);
	outer->setContentsMargins(8, 8, 8, 8);
	outer->setSpacing(8);

	auto* nameRow = new QHBoxLayout;
	nameRow->addWidget(new QLabel(QStringLiteral("トラック名:"), page));
	auto* nameEdit = new QLineEdit(track->name(), page);
	nameRow->addWidget(nameEdit, 1);
	outer->addLayout(nameRow);
	connect(nameEdit, &QLineEdit::textEdited, track, &InstrumentTrack::setName);
	connect(track, &Track::nameChanged, nameEdit, [track, nameEdit]
	{
		if (nameEdit->text() != track->name()) { nameEdit->setText(track->name()); }
	});

	auto* stateRow = new QHBoxLayout;
	auto* mute = new AutomatableButton(page, QStringLiteral("ミュート"));
	mute->setModel(track->getMutedModel());
	mute->setCheckable(true);
	mute->setText(QStringLiteral("ミュート"));
	mute->setToolTip(QStringLiteral("このトラックを消音します"));
	mute->setMinimumWidth(90);
	stateRow->addWidget(mute);
	auto* solo = new AutomatableButton(page, QStringLiteral("ソロ"));
	solo->setModel(track->getSoloModel());
	solo->setCheckable(true);
	solo->setText(QStringLiteral("ソロ"));
	solo->setToolTip(QStringLiteral("このトラックだけを再生します"));
	solo->setMinimumWidth(90);
	stateRow->addWidget(solo);
	stateRow->addStretch();
	outer->addLayout(stateRow);

	auto* controls = new QGridLayout;
	controls->setHorizontalSpacing(12);
	controls->setVerticalSpacing(4);

	auto addControl = [page, controls](QWidget* control,
			const QString& label, int column)
	{
		controls->addWidget(control, 0, column, Qt::AlignHCenter);
		auto* text = new QLabel(label, page);
		text->setAlignment(Qt::AlignHCenter);
		controls->addWidget(text, 1, column);
		controls->setColumnStretch(column, 1);
	};

	auto* volume = new VolumeKnob(KnobType::Bright26, page, QStringLiteral("音量"));
	volume->setModel(track->volumeModel());
	volume->setHintText(QStringLiteral("音量:"), "%");
	addControl(volume, QStringLiteral("音量"), 0);

	auto* pan = new Knob(KnobType::Bright26, page, QStringLiteral("パン"));
	pan->setModel(track->panningModel());
	pan->setHintText(QStringLiteral("パン:"), "");
	addControl(pan, QStringLiteral("パン"), 1);

	auto* pitch = new Knob(KnobType::Bright26, page, QStringLiteral("ピッチ"));
	pitch->setModel(track->pitchModel());
	pitch->setHintText(QStringLiteral("ピッチ:"), QStringLiteral(" セント"));
	addControl(pitch, QStringLiteral("ピッチ"), 2);

	auto* pitchRange = new LcdSpinBox(2, page, QStringLiteral("ピッチベンド幅"));
	pitchRange->setModel(track->pitchRangeModel());
	pitchRange->setToolTip(QStringLiteral("ピッチベンドの範囲（半音）"));
	addControl(pitchRange, QStringLiteral("ベンド幅"), 3);

	auto* mixer = new LcdSpinBox(2, page, QStringLiteral("ミキサーチャンネル"));
	mixer->setModel(track->mixerChannelModel());
	addControl(mixer, QStringLiteral("ミキサー"), 4);

	outer->addLayout(controls);

	auto* globalTranspose = new LedCheckBox(
			QStringLiteral("全体移調をこのトラックへ適用"), page,
			QStringLiteral("全体移調"), LedCheckBox::LedColor::Green, false);
	globalTranspose->setModel(track->useMasterPitchModel());
	globalTranspose->setToolTip(QStringLiteral(
			"オンにすると、狐Tone全体のマスターピッチ変更に合わせてこのトラックも移調します。"));
	outer->addWidget(globalTranspose);

	auto* tuningHelp = new QLabel(QStringLiteral(
			"VST3音源の微分音・スケール設定は、音源GUI側のチューニング機能を使用します。"), page);
	tuningHelp->setWordWrap(true);
	outer->addWidget(tuningHelp);

	auto* save = new QPushButton(QStringLiteral("トラックプリセットを保存..."), page);
	connect(save, &QPushButton::clicked, this,
			[this, track] { saveTrackPreset(track); });
	outer->addWidget(save);

	outer->addStretch();
	auto* keyboardLabel = new QLabel(QStringLiteral("キーボード"), page);
	outer->addWidget(keyboardLabel);
	auto* piano = new PianoView(page);
	piano->setModel(track->pianoModel());
	piano->setMinimumHeight(100);
	piano->setMaximumHeight(100);
	outer->addWidget(piano);
	return page;
}




void Vst3InstrumentView::saveTrackPreset(InstrumentTrack* track)
{
	if (track == nullptr) { return; }

	const QString presetRoot = ConfigManager::inst()->userPresetsDir();
	const QString instrumentDir = presetRoot + track->instrumentName();
	QDir().mkpath(instrumentDir);

	FileDialog dialog(this, QStringLiteral("トラックプリセットを保存"), instrumentDir,
			QStringLiteral("XMLプリセットファイル (*.xpf)"));
	dialog.setAcceptMode(FileDialog::AcceptSave);
	dialog.setDirectory(instrumentDir);
	dialog.setFileMode(FileDialog::AnyFile);
	QString fileName = track->name();
	dialog.selectFile(fileName.remove(QRegularExpression(FILENAME_FILTER)));
	dialog.setDefaultSuffix("xpf");

	if (dialog.exec() != QDialog::Accepted || dialog.selectedFiles().isEmpty()
			|| dialog.selectedFiles().first().isEmpty())
	{
		return;
	}

	DataFile dataFile(DataFile::Type::InstrumentTrackSettings);
	QDomElement& content = dataFile.content();
	track->savePreset(dataFile, content);
	content.setAttribute("muted", 0);
	content.setAttribute("solo", 0);
	content.setAttribute("mutedBeforeSolo", 0);
	dataFile.writeFile(dialog.selectedFiles().first());
}




void Vst3InstrumentView::showEvent(QShowEvent* event)
{
	InstrumentView::showEvent(event);
	// drop the plug-in-logo window icon (the red square in the title bar)
	if (auto* w = instrumentTrackWindow()) { w->setWindowIcon(QIcon()); }
	// embed the native editor the first time the window is shown, so plug-in
	// GUIs aren't created before the instrument is actually opened
	ensureEmbedded();
}




void Vst3InstrumentView::ensureEmbedded()
{
	if (m_pluginView != nullptr) { m_pluginView->ensureEmbeddedEditor(); }
}




void Vst3InstrumentView::fitWindow()
{
	// Grow the instrument window to fit the embedded GUI. This view is the whole
	// window content (added straight into the window's layout), so the window's
	// own size hint already accounts for the tab bar and the embedded plug-in
	// GUI - grow to it, but never shrink below the current size.
	auto* w = instrumentTrackWindow();
	if (w == nullptr) { return; }

	if (layout() != nullptr) { layout()->activate(); }
	if (w->layout() != nullptr) { w->layout()->activate(); }
	const QSize want = w->sizeHint().expandedTo(w->size());
	if (want != w->size())
	{
		w->resize(want);
		if (w->parentWidget() != nullptr)
		{
			w->parentWidget()->resize(w->parentWidget()->sizeHint());
		}
	}
}




void Vst3InstrumentView::modelChanged()
{
	// the plug-in name is shown in the window title bar; nothing to do here
}




} // namespace gui


extern "C"
{

// necessary for getting instance out of shared lib
PLUGIN_EXPORT Plugin* lmms_plugin_main(Model* m, void*)
{
	return new Vst3Instrument(static_cast<InstrumentTrack*>(m));
}

}


} // namespace lmms
